In [1]:
import numpy as np
data = []
baris = 0
kolom = 7
bobot = []

In [2]:
def deklarasi_ukuranData():
    global data
    global baris
    global kolom
    #deklarasi matrix sementara
    baris = int(input("Masukkan Jumlah Baris Data : "))
    data = np.zeros((baris, kolom), dtype=object)
    print("Data Sementara : ")
    print(data)
    print("Ukuran Data : ", data.shape)

In [3]:
def input_data():
    global data
    global baris
    global kolom
    #input data ke matrix
    for x in range(baris):
        for y in range(kolom):
            if y == 0:
                print("Masukkan Daerah Lokasi Gudang", x+1)
                a = str(input())
                data[x][y] = a
            elif y == 1:
                print("Masukkan Jarak dengan Pasar Terdekat (km)")
                a = float(input())
                data[x][y] = a
            elif y == 2:
                print("Masukkan Kepadatan Penduduk Disekitar Gudang")
                a = float(input())
                data[x][y] = a
            elif y == 3:
                print("Masukkan Jarak dari Pabrik (km)")
                a = float(input())
                data[x][y] = a
            elif y == 4:
                print("Masukkan Jarak dengan Gudang yang Sudah Ada")
                a = float(input())
                data[x][y] = a
            elif y == 5:
                print("Masukkan Harga Tanah untuk Lokasi (x1000 Rp/m2)")
                a = float(input())
                data[x][y] = a

In [4]:
def input_bobot():
    global bobot
    global kolom
    totalBobot = 0
    jumlahKriteria = kolom
    bobot = np.zeros(kolom)
    for y in range(kolom):
        if y == 0 or y == 6:
            bobot[y] = 0
        elif y == 1:
            print("Masukan Nilai Bobot Jarak dengan Pasar Terdekat")
            a = float(input())
            bobot[y] = a
        elif y == 2:
            print("Masukan Nilai Bobot Kepadatan Penduduk Disekitar Gudang")
            a = float(input())
            bobot[y] = a
        elif y == 3:
            print("Masukan Nilai Bobot Jarak dari Pabrik")
            a = float(input())
            bobot[y] = a
        elif y == 4:
            print("Masukan Nilai Bobot Jarak dengan Gudang yang Sudah Ada")
            a = float(input())
            bobot[y] = a
        elif y == 5:
            print("Masukkan Nilai Bobot Harga Tanah untuk Lokasi (x1000 Rp/m2)")
            a = float(input())
            bobot[y] = a         
    print("Nilai Bobot Penilaian Sementara :")
    print(bobot)
    
    #Perhitungan total bobot
    for y in range(jumlahKriteria):
        totalBobot = totalBobot + bobot[y]
    print("Total Nilai Bobot :")
    print(totalBobot)
    
    #Perbaikan bobot setiap kriteria
    for y in range(jumlahKriteria):
        bobot[y] = bobot[y]/totalBobot
        if y == 1 or y == 3 or y == 5:
            bobot[y] = -abs(bobot[y])
    print("Nilai Bobot Penilaian Baru :")
    print(bobot)

In [5]:
def WP():
    global data
    global baris
    global kolom
    #Menghitung nilai vektor S
    for y in range(kolom):
        if y == 0 or y == 6:
            continue
        for x in range(baris):
            data[x][y] = pow(data[x][y], bobot[y])
    print("Data Saat Ini : ")
    print(data)
    
    #Menghitung nilai vektor S
    totalS = 0
    for x in range(baris):
        v = 1
        for y in range(kolom):
            if y == 0 or y == 6:
                continue
            v = v * data[x][y]
            data[x][6] = v
    for x in range(baris):
        totalS = totalS + data[x][6]
    print("Total Nilai Vektor S : ")
    print(totalS)

    #Menghitung nilai vektor V
    for x in range(baris):
        data[x][6] = data[x][6]/totalS
    print("Hasil Perhitungan WP :")
    print(data)
    
    #Hasil Perangkingan
    print("Hasil Akhir Perangkingan")
    hasil = data[data[:, 6].argsort()][::-1]
    print("Nomor Lokasi : ", hasil[0][0])
    print("Nilai Akhir Perangkingan Lokasi : ", hasil[0][6])

In [6]:
def menu():
    print("\nPilih Operasi : ")
    print("1. Deklarasi Banyak Data")
    print("2. Input Data")
    print("3. Kosongkan Data")
    print("4. Lihat Data")
    print("5. Input Bobot Kriteria")
    print("6. Perangkingan dengan WP")

In [7]:
def main():
    menu()
    global data
    pilihan = int(input("Masukkan Pilihan Operasi : "))
    if pilihan == 1:
        deklarasi_ukuranData()
        main()
    elif pilihan == 2:
        input_data()
        main()
    elif pilihan == 3:
        data = np.zeros((2, 2))
        main()
    elif pilihan == 4:
        print("Data Saat Ini : ")
        print(data)
        main()
    elif pilihan == 5:
        input_bobot()
        main()
    elif pilihan == 6:
        WP()
        main()
    else :
        print("Pilihan Tidak Tersedia")

In [8]:
main()


Pilih Operasi : 
1. Deklarasi Banyak Data
2. Input Data
3. Kosongkan Data
4. Lihat Data
5. Input Bobot Kriteria
6. Perangkingan dengan WP
Masukkan Pilihan Operasi : 1
Masukkan Jumlah Baris Data : 3
Data Sementara : 
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Ukuran Data :  (3, 7)

Pilih Operasi : 
1. Deklarasi Banyak Data
2. Input Data
3. Kosongkan Data
4. Lihat Data
5. Input Bobot Kriteria
6. Perangkingan dengan WP
Masukkan Pilihan Operasi : 5
Masukan Nilai Bobot Jarak dengan Pasar Terdekat
5
Masukan Nilai Bobot Kepadatan Penduduk Disekitar Gudang
3
Masukan Nilai Bobot Jarak dari Pabrik
4
Masukan Nilai Bobot Jarak dengan Gudang yang Sudah Ada
4
Masukkan Nilai Bobot Harga Tanah untuk Lokasi (x1000 Rp/m2)
2
Nilai Bobot Penilaian Sementara :
[0. 5. 3. 4. 4. 2. 0.]
Total Nilai Bobot :
18.0
Nilai Bobot Penilaian Baru :
[ 0.         -0.27777778  0.16666667 -0.22222222  0.22222222 -0.11111111
  0.        ]

Pilih Operasi : 
1. Deklarasi Banyak Data
2. Input Data
3. Kosongkan Data
4

In [1]:
print ("Lalapan")

Lalapan


In [2]:
for x in range (10):
    print (x)

0
1
2
3
4
5
6
7
8
9
